### ISSUE TITLE
Enable uploading datasets to dashboard

### ISSUE THREAD

**Issue by egrace479** [Imageomics/dashboard-prototype#23]
Add upload data option to dashboard. Also requires generalizing Dashboard functions to take in CSV or XLS with particular columns.

Resolves a few steps in #15.

**Comment by hlapp** [comment]
I'm not sure I would worry much about accepting XLS. It's not considered an interoperable format, and is not really difficult to convert to CSV.

**Comment by egrace479** [comment]
I currently have it set up to do so in the [feature/upload](https://github.com/Imageomics/dashboard-prototype/tree/feature/upload) branch. I could remove it if you think it's more problematic to have that functionality? I just have a couple minor tweaks to make and I'll be ready to open a PR to close this.

**Comment by hlapp** [comment]
Oh if you have that already, needn't really take it out again. Although one problem with XLS is that it's not well determined where the data is (which spreadsheet? starting in which row and column? ignore what follows after some row and/or column? etc). But presumably the expectation is that it has to be the first spreadsheet, starting at first row and column, taking up the entire spreadsheet?
