### ISSUE TITLE
Remove debug setting for production deployment

### ISSUE THREAD

**Issue by johnbradley** [Imageomics/dashboard-prototype#42]
Right now we are running production with debug enabled:
https://github.com/Imageomics/dashboard-prototype/blob/09c8cd3f8c412a8eb97d3ec61dbb8b41634d0418/dashboard.py#L336
This could potentially contribute to performance issues.
The run_server function is a deprecated alias of run.
Here is the docs for run: https://dash.plotly.com/reference#app.run
The debug flag is passed to Flask.debug setting.
Here is some documentation from Flask on issues with production/debug https://flask.palletsprojects.com/en/2.3.x/debugging/

**Comment by egrace479** [comment]
So, we should switch to `app.run`? It seems that's still not advisable for production--is this something we should consider?

**Comment by egrace479** [comment]
> So, we should switch to `app.run`? It seems that's still not advisable for production:
> 
> > WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
> 
> --is this something we should consider?

There are multiple [options](https://flask.palletsprojects.com/en/2.3.x/deploying/) for deployment method. With the [HF Spaces implementation](https://huggingface.co/spaces/imageomics/dashboard-prototype), we use [gunicorn](https://flask.palletsprojects.com/en/2.3.x/deploying/gunicorn/) with a Dockerfile, and this seems to perform well.
