### ISSUE TITLE
Single errors in lat and lon break the map

### ISSUE THREAD

**Issue by omnomdombomb** [Imageomics/dashboard-prototype#48]
If the **lat** or **lon** values are incorrectly formatted they with be read as integers instead of floats. This breaks the entire map dashboard. Code should be added to ignore these errors.

**Comment by egrace479** [comment]
> If the **lat** or **lon** values are incorrectly formatted they with be read as integers instead of floats. This breaks the entire map dashboard. Code should be added to ignore these errors.

Yes, I believe it's problematic when the `lat` value is outside [-90, 90] or `lon` is outside [-180, 180]. I can add a check for that while processing the data to remove problematic values.

**Comment by egrace479** [comment]
Addressed in PR #50 to the [`dev` branch](https://github.com/Imageomics/dashboard-prototype/tree/dev). Will be implemented in v1.1.0.
